### ISSUE TITLE
Error on require line

### ISSUE THREAD

**Issue by ALEKSEYR554** [ifokeev/telegraph_api_ruby#1]
Can not run any program after writing `require 'telegraph_api_ruby'` i just simply getting an error
I tried updating all gems and it didn't help
Code
```
require 'telegraph_api_ruby'
puts "test"
```
Error
```
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/nominal.rb:32:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/any.rb:9:in `initialize'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/any.rb:34:in `new'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/any.rb:34:in `<module:Types>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/any.rb:2:in `<module:Dry>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/any.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types/core.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry/types.rb:173:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-types-0.15.0/lib/dry-types.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-struct-0.7.0/lib/dry/struct.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/dry-struct-0.7.0/lib/dry-struct.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/telegraph_api_ruby-1.0.1/lib/telegraph_api_ruby/types/core.rb:1:in `<top (required)>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/telegraph_api_ruby-1.0.1/lib/telegraph_api_ruby/types.rb:1:in `require_relative'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/telegraph_api_ruby-1.0.1/lib/telegraph_api_ruby/types.rb:1:in `<top (required)>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/telegraph_api_ruby-1.0.1/lib/telegraph_api_ruby.rb:1:in `require_relative'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/telegraph_api_ruby-1.0.1/lib/telegraph_api_ruby.rb:1:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from C:/Users/amoru/Documents/telega_bot/12.rb:1:in `<main>'
<internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- telegraph_api_ruby (LoadError)
	from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/Users/amoru/Documents/telega_bot/12.rb:1:in `<main>'
[Finished in 1.375s]
```
Any help?

**Comment by ifokeev** [comment]
It looks like `dry-types` has updated. Try to provide a strict version `0.12` for `dry-types`.

**Comment by ALEKSEYR554** [comment]
> It looks like `dry-types` has updated. Try to provide a strict version `0.12` for `dry-types`.

Didn't work
